### ISSUE TITLE
astro-compress is gone from NPM registry

### ISSUE THREAD

**Issue by saif71** [astro-community/astro-compress#163] opened 2023-08-06 08:32 UTC
Like the title suggest. It is gone from the NPM registry.
https://www.npmjs.com/package/astro-compress

![image](https://github.com/astro-community/astro-compress/assets/6561498/6dd457fa-5144-4a49-b0a1-af5fb4f7de35)

**Comment by ToxiWoxi** [comment] 2023-08-06 08:34
#162

**Comment by mwaldheim** [comment] 2023-08-06 09:11
How long will it take? My website is down now... because my pipeline can't do a rebuild.

**Comment by Xanonymous-GitHub** [comment] 2023-08-06 15:05
same problem here.

**Comment by benstegink** [comment] 2023-08-06 15:22
same problem for me as well :(

**Comment by saif71** [comment] 2023-08-06 15:24
Guess this is the life with open source. I suggest you :
1. temporarily remove the package from your project (I did it this evening.)
2. Use another similar package for now.

**Comment by itaispector** [comment] 2023-08-06 21:04
> 

same here

**Comment by Defkil** [comment] 2023-08-06 21:30
@itaispector
https://www.npmjs.com/package/@otterlord/astro-compress

**Comment by itaispector** [comment] 2023-08-06 21:47
> @itaispector https://www.npmjs.com/package/@otterlord/astro-compress

thanks buddy 🙏

**Comment by felixsanz** [comment] 2023-08-07 01:23
@NikolaRHristov can you take a look at this please?

**Comment by NikolaRHristov** [comment] 2023-08-07 02:08
Ok, I have regained access to the `astro-compress`, `critters`, `rome` and `files-pipe` packages. These will be republished.

**Comment by NikolaRHristov** [comment] 2023-08-07 02:29
After I have republished I will transfer over the packages to @FredKSchott, if that's okay.

**Comment by zoxon** [comment] 2023-08-07 07:21
@NikolaRHristov Why is version 2.0.0 [empty in NPM](https://npmfs.com/package/astro-compress/2.0.0/)? Can you please fix it?

**Comment by jmblog** [comment] 2023-08-07 12:20
Build seems to fail when using v2.0.0.

```
 error   Failed to resolve entry for package "astro-compress". The package may have incorrect main/module/exports specified in its package.json.
  File:
    /Users/path/to/astro.config.mjs
```

**Comment by benstegink** [comment] 2023-08-07 12:37
I'm receiving the same error as @jmblog

**Comment by Igloczek** [comment] 2023-08-07 13:27
Can you please release 1.1.50?

**Comment by NikolaRHristov** [comment] 2023-08-07 16:04
Hello, @zoxon, version 2.0 is empty as to not get malwared. @jmblog, @benstegink just use @otterlord/astro-compress in the meantime while this gets fixed. @Igloczek, no because it uses `files-pipe` which is currently missing. These will all be resolved by the end of the day. NPM does not allow republishing of packages over 24 hours so I have to wait and their support haven't answered me still. This is why I'm republishing empty packages as to them not getting malwared and everything will be fixed. I have the source code offline.

**Comment by candidosales** [comment] 2023-08-07 19:27
+1

**Comment by RodrigoTomeES** [comment] 2023-08-07 21:23
What happened to astro-compress and atstro-critters?

**Comment by torchsmith** [comment] 2023-08-07 23:04
+1

**Comment by aetherclouds** [comment] 2023-08-08 05:56
> The author closed their NPM account; they'll make a new one shortly #162

why?

**Comment by saif71** [comment] 2023-08-08 05:58
@aetherclouds Bro wok up in the morning and choose violence. 😂

**Comment by NikolaRHristov** [comment] 2023-08-08 06:07
> > @aetherclouds Bro wok up in the morning and choose violence. 😂
> 
> just genuinely curious, sorry if it came off the wrong way!

Hi, I'm exiting Open-Source, if that's a thing, and just did it the wrong way. I thought it would archive the packages leaving everything intact. Now two more days days of pressure 😅.

Progress so far:
 - The build scripts have been recreated - https://npmjs.org/baxast
 - The `files-pipe` component is also up - https://npmjs.org/files-pipe
 
 I should get `astro-compress`, `astro-critters` and `astro-rome` up in a few hours, as well. Just testing a few more things and making sure everything is working correctly.

**Comment by aetherclouds** [comment] 2023-08-08 06:17
> > > @aetherclouds Bro wok up in the morning and choose violence. 😂
> > 
> > 
> > just genuinely curious, sorry if it came off the wrong way!
> 
> Hi, I'm exiting Open-Source, if that's a thing, and just did it the wrong way. I thought it would archive the packages leaving everything intact. Now two more days days of pressure 😅.
> 
> Progress so far:
> 
> * The build scripts have been recreated - https://npmjs.org/baxast
> * The `files-pipe` component is also up - https://npmjs.org/files-pipe
> 
> I should get `astro-compress`, `astro-critters` and `astro-rome` up in a few hours, as well. Just testing a few more things and making sure everything is working correctly.

don't down on yourself I'm sure nobody would predict something like that happening right upon deleting their account :)
good luck on your new ventures and thanks for the neat libraries!

**Comment by NikolaRHristov** [comment] 2023-08-08 06:20
😅 Thank you! @aetherclouds

**Comment by RodrigoTomeES** [comment] 2023-08-08 06:24
@NikolaRHristov so if I understand it correctly, you removed your NPM account before transfer that packages to @FredKSchott but what about this you said  "Hello, @zoxon, version 2.0 is empty as to not get malwared". Before the packages had malware?

**Comment by NikolaRHristov** [comment] 2023-08-08 06:36
I setup a script to automatically re-publish those packages. The packages were empty because some things were not working correctly and I just didn't want to publish broken packages, so just empty ones seemed a better alternative.

You can still see the source online there is no malware there.

Also, I publish all of my packages with [Provenance](https://docs.npmjs.com/generating-provenance-statements), which means that they are verified by a commit and published from GitHub. You can still see the little box at the bottom https://www.npmjs.com/package/files-pipe
![image](https://github.com/astro-community/astro-compress/assets/90222871/ab9fef53-0bf7-4b91-ac7e-d3b7d296f85c)

This is how `astro-compress`, astro-critters and `astro-rome` were and will also be published in the future, as well.

**Comment by RodrigoTomeES** [comment] 2023-08-08 06:54
> I setup a script to automatically re-publish those packages. The packages were empty because some things were not working correctly and I didn't want to publish broken packages, so just empty ones seemed a better alternative.
> 
> You can still see the source online. There is no malware there.
> 
> Also, I publish all of my packages with [Provenance](https://docs.npmjs.com/generating-provenance-statements), which means that they are verified by a commit and published from GitHub. You can still see the little box at the bottom https://www.npmjs.com/package/files-pipe ![image](https://user-images.githubusercontent.com/90222871/259005518-ab9fef53-0bf7-4b91-ac7e-d3b7d296f85c.png)
> 
> This is how `astro-compress`, `astro-critters` and `astro-rome` were and will also be published in the future, as well.

Okay I understand, you republished the package to prevent some get the package name and distribute malware. And not that your package had malware.

**Comment by NikolaRHristov** [comment] 2023-08-08 07:00
> Okay I understand, you republished the package to prevent some get the package name and distribute malware. And not that your package had malware.

Yes, correct, as a per-emptive measure.

**Comment by jamaluddinrumi** [comment] 2023-08-08 07:53
> > > @aetherclouds Bro wok up in the morning and choose violence. 😂
> 
> > 
> 
> > just genuinely curious, sorry if it came off the wrong way!
> 
> 
> 
> Hi, I'm exiting Open-Source, if that's a thing, and just did it the wrong way. I thought it would archive the packages leaving everything intact. Now two more days days of pressure 😅.
> 
> 
> 
> Progress so far:
> 
>  - The build scripts have been recreated - https://npmjs.org/baxast
> 
>  - The `files-pipe` component is also up - https://npmjs.org/files-pipe
> 
>  
> 
>  I should get `astro-compress`, `astro-critters` and `astro-rome` up in a few hours, as well. Just testing a few more things and making sure everything is working correctly.

you deserve an award, honestly

**Comment by NikolaRHristov** [comment] 2023-08-08 08:42
> > > > @aetherclouds Bro wok up in the morning and choose violence. 😂
> > 
> > 
> > > 
> > 
> > 
> > > just genuinely curious, sorry if it came off the wrong way!
> > 
> > 
> > Hi, I'm exiting Open-Source, if that's a thing, and just did it the wrong way. I thought it would archive the packages leaving everything intact. Now two more days days of pressure 😅.
> > Progress so far:
> > 
> > * The build scripts have been recreated - https://npmjs.org/baxast
> > * The `files-pipe` component is also up - https://npmjs.org/files-pipe
> > 
> > I should get `astro-compress`, `astro-critters` and `astro-rome` up in a few hours, as well. Just testing a few more things and making sure everything is working correctly.
> 
> you deserve an award, honestly

That would be @TheOtterlord, he pulled up and created a backup, archive and published everything almost the next day, so that nothing is lost and transitions can be made.

**Comment by KyTiXo** [comment] 2023-08-08 16:18
Thanks for the healthy reminder to always check the issues page haha

Tried to remove the compress package out of fear of malware and our CI bundle went from 26mb to 156mb 🤣

**Comment by NikolaRHristov** [comment] 2023-08-08 23:24
[astro-compress](https://www.npmjs.com/package/astro-compress) v2.0.1 has been restored with [Provenance ](https://github.com/baxast/astro-compress/actions/runs/5802889025/attempts/1)

This repository https://github.com/baxast/astro-compress will soon be synchronized with the official `astro-community` one https://github.com/astro-community/astro-compress.

You can submit issues in either.

`astro-critters` and `astro-rome` coming up next.

**Comment by nathsimpson** [comment] 2023-08-08 23:41
Thanks for the hustle! Well done 👍

**Comment by NikolaRHristov** [comment] 2023-08-08 23:42
Pog

**Comment by NikolaRHristov** [comment] 2023-08-09 08:26
`astro-critters` up too - https://github.com/astro-community/astro-critters/issues/137 v2.0.2

**Comment by jmblog** [comment] 2023-08-09 12:07
I tried v2.0.2, but the `exclude` option appears to be ignored. I recall that it worked in the previous version.

```js
import compress from "astro-compress";

export default {
    integrations: [
        compress({
            exclude: [
                'dist/images/articles/*',
                'dist/images/banners/*',
                'dist/images/experts/*',
                'dist/images/top_banners/*',
            ],
        }),
    ],
};
```

**Comment by NikolaRHristov** [comment] 2023-08-09 21:16
> I tried v2.0.2, but the `exclude` option appears to be ignored. I recall that it worked in the previous version.
> 
> ```js
> import compress from "astro-compress";
> 
> export default {
>     integrations: [
>         compress({
>             exclude: [
>                 'dist/images/articles/*',
>                 'dist/images/banners/*',
>                 'dist/images/experts/*',
>                 'dist/images/top_banners/*',
>             ],
>         }),
>     ],
> };
> ```

Try `Exclude`

**Comment by Morteza-Mazrae** [comment] 2023-08-10 11:33
@NikolaRHristov hey, I add [astro-compress](https://www.npmjs.com/package/astro-compress) v2.0.2 to my app and got such errors:

-  The package "stream" wasn't found on the file system but is built into node.
- The package "stream" wasn't found on the file system but is built into node.
- 'etc...'  into node.

If I remove  [astro-compress](https://www.npmjs.com/package/astro-compress) v2.0.2  and add [@otterlord/astro-compress](https://www.npmjs.com/package/@otterlord/astro-compress) everything is fine in local but the issue is nothing appears on the app (white blank page after Cloudflare deployment)

**Comment by NikolaRHristov** [comment] 2023-08-10 11:47
> * stream

Hi, does this happen with the latest version `v2.0.5`?

**Comment by Morteza-Mazrae** [comment] 2023-08-10 12:01
> Hi, does this happen with the latest version v2.0.5? 

I update it to the latest version and yes the issue still there

**Comment by Morteza-Mazrae** [comment] 2023-08-10 12:01
> Hi, does this happen with the latest version v2.0.5? 

I update it to the latest version and yes the issue still there

**Comment by NikolaRHristov** [comment] 2023-08-10 12:30
Could you please share your `tsconfig.json` or some more information like build logs, etc. so we can debug this further. You can do message me privately on Discord at `nikolahristov`

**Closed** 2023-08-14 02:06 UTC
